services:
  - type: web
    name: mood-music-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
